[package]
name = "create-account-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
radix-transactions = "1.3"
radix-common = "1.3"
radix-engine-interface = "1.3"
inquire = "0.7"
anyhow = "1"
hex = "0.4"
